server:
  port: 9090
spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false # in properties file we would use -> spring.jpa.open-in-view = false

app:
  sample-text: This text is from config
